// @vitest-environment node
//
// Pure color math over text — no DOM needed, so this opts out of the jsdom
// default (see vitest.config.ts) same as theme-parity.test.ts.
//
// Asserts every theme's foreground/background token pair meets its WCAG 2.1
// AA contrast threshold, for both :root (light) and .dark. This is the CI
// gate; docs/accessibility/contrast.md (regenerated by
// `node scripts/check-contrast.mjs`) is the recorded, human-readable numbers
// behind it — the two share their math (scripts/lib/color-contrast.mjs) so
// they can't drift against each other. See ADR-0014.
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { scoreThemeMode, tokensInBlock } from "../../scripts/lib/color-contrast.mjs";

const THEMES_DIR = join(__dirname, "../styles/themes");

const themeFiles = readdirSync(THEMES_DIR).filter((file) => file.endsWith(".css"));

describe("theme token contrast (WCAG 2.1 AA)", () => {
	it("found theme files to check", () => {
		expect(themeFiles.length).toBeGreaterThan(0);
	});

	for (const file of themeFiles) {
		const theme = file.replace(/\.css$/, "");
		const css = readFileSync(join(THEMES_DIR, file), "utf-8");

		for (const [mode, selector] of [
			["light", ":root"],
			["dark", "\\.dark"],
		] as const) {
			describe(`${theme} (${mode})`, () => {
				const tokens = tokensInBlock(css, selector);
				const results = scoreThemeMode(tokens);

				it("scored at least one token pair", () => {
					expect(results.length).toBeGreaterThan(0);
				});

				it.each(results)("`$fg` on `$bg` meets $minRatio:1", ({ ratio, minRatio, pass }) => {
					expect(pass, `contrast ${ratio.toFixed(2)}:1, needs ${minRatio}:1`).toBe(true);
				});
			});
		}
	}
});
