// Compile every theme in src/styles/themes/ into dist/themes/<feel>.css (each a
// self-contained stylesheet: utilities + that feel's tokens + fonts), copy the
// font files, and alias the default feel to dist/styles.css. Adding a new theme
// file is picked up automatically — no script or exports change needed (the
// package.json "./themes/*" export is a wildcard).
//
// Also resolves the default theme's CSS custom properties to literal values
// (see scripts/generate-tokens.mjs) and appends them to dist/tokens.{mjs,d.ts}
// — tsup already built those from src/tokens.ts (spacing/fontSize/fontWeight,
// which have no CSS backing); this runs after tsup so it can add the
// theme-derived `light`/`dark`/`radii`/`fontFamily` exports and the combined
// `tokens` object without either build step needing to know about the other's
// output ahead of time.
import { execFileSync } from "node:child_process";
import { cpSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolveThemeTokens } from "./generate-tokens.mjs";

const DEFAULT_THEME = "modern-neutral";
const themesDir = "src/styles/themes";

mkdirSync("dist/themes", { recursive: true });
const themes = readdirSync(themesDir).filter((f) => f.endsWith(".css"));

for (const file of themes) {
	const name = file.replace(/\.css$/, "");
	execFileSync("tailwindcss", ["-i", `${themesDir}/${file}`, "-o", `dist/themes/${name}.css`, "--minify"], {
		stdio: "inherit",
	});
}

// Fonts sit next to the theme CSS (dist/themes/), since each theme's @font-face
// uses "./fonts/..." relative to its own location.
cpSync("src/styles/fonts", "dist/themes/fonts", { recursive: true });
// Default stylesheet re-exports the default theme so its font url()s still
// resolve from dist/themes/.
writeFileSync("dist/styles.css", `@import "./themes/${DEFAULT_THEME}.css";\n`);
console.log(`built ${themes.length} theme(s): ${themes.map((t) => t.replace(/\.css$/, "")).join(", ")}`);

// --- Append resolved theme tokens to dist/tokens.{mjs,d.ts} --------------

const defaultThemeCss = readFileSync(`${themesDir}/${DEFAULT_THEME}.css`, "utf-8");
const resolved = resolveThemeTokens(defaultThemeCss);

/** Render a flat string-valued object as a JS object literal, one key per line. */
function jsObjectLiteral(obj, indent = "\t") {
	const entries = Object.entries(obj)
		.map(([key, value]) => `${indent}${key}: ${JSON.stringify(value)},`)
		.join("\n");
	return `{\n${entries}\n}`;
}

/** Render a flat string-valued object as a TS object *type*, one key per line
 *  with literal string types (mirrors what tsup/dts emits for an `as const`
 *  object, so `light`/`dark`/`radii`/`fontFamily` read the same as the
 *  tsup-built `spacing`/`fontSize`/`fontWeight` above them in this file). */
function tsObjectType(obj, indent = "\t") {
	const entries = Object.entries(obj)
		.map(([key, value]) => `${indent}readonly ${key}: ${JSON.stringify(value)};`)
		.join("\n");
	return `{\n${entries}\n}`;
}

const tokensMjs = readFileSync("dist/tokens.mjs", "utf-8");
writeFileSync(
	"dist/tokens.mjs",
	`${tokensMjs}
// --- Generated by scripts/build-css.mjs from src/styles/themes/${DEFAULT_THEME}.css. ---
// Resolved literal values — no var(--x) — for canvas/SVG/email use, where
// there's no DOM to resolve a CSS custom property against.
var light = {
  colors: ${jsObjectLiteral(resolved.light.colors, "    ").replaceAll("\n", "\n  ")},
  shadows: ${jsObjectLiteral(resolved.light.shadows, "    ").replaceAll("\n", "\n  ")}
};
var dark = {
  colors: ${jsObjectLiteral(resolved.dark.colors, "    ").replaceAll("\n", "\n  ")},
  shadows: ${jsObjectLiteral(resolved.dark.shadows, "    ").replaceAll("\n", "\n  ")}
};
var radii = ${jsObjectLiteral(resolved.radii, "  ")};
var fontFamily = ${jsObjectLiteral(resolved.fontFamily, "  ")};
var tokens = {
  light,
  dark,
  radii,
  spacing,
  fontSize,
  fontWeight,
  fontFamily
};

export { dark, fontFamily, light, radii, tokens };
`,
);

const tokensDts = readFileSync("dist/tokens.d.ts", "utf-8");
writeFileSync(
	"dist/tokens.d.ts",
	`${tokensDts}
// --- Generated by scripts/build-css.mjs from src/styles/themes/${DEFAULT_THEME}.css. ---
/** Resolved literal values (colors, shadows) for the default theme's light
 *  mode — no var(--x) — usable outside a DOM styling context: chart
 *  libraries, canvas/SVG rendering, email templates. */
export declare const light: {
\treadonly colors: ${tsObjectType(resolved.light.colors, "\t\t").replaceAll("\n", "\n\t")};
\treadonly shadows: ${tsObjectType(resolved.light.shadows, "\t\t").replaceAll("\n", "\n\t")};
};
/** Same as \`light\`, resolved from the theme's \`.dark\` block. */
export declare const dark: {
\treadonly colors: ${tsObjectType(resolved.dark.colors, "\t\t").replaceAll("\n", "\n\t")};
\treadonly shadows: ${tsObjectType(resolved.dark.shadows, "\t\t").replaceAll("\n", "\n\t")};
};
/** Border-radius scale, resolved to literal pixel values. Mode-independent —
 *  the theme has no \`.dark\` override for radius. */
export declare const radii: ${tsObjectType(resolved.radii)};
/** Font stacks, resolved to literal face names. Mode-independent. */
export declare const fontFamily: ${tsObjectType(resolved.fontFamily)};
export declare const tokens: {
\treadonly light: typeof light;
\treadonly dark: typeof dark;
\treadonly radii: typeof radii;
\treadonly spacing: typeof spacing;
\treadonly fontSize: typeof fontSize;
\treadonly fontWeight: typeof fontWeight;
\treadonly fontFamily: typeof fontFamily;
};
export type Tokens = typeof tokens;
`,
);

console.log("resolved theme tokens → dist/tokens.mjs, dist/tokens.d.ts");
